### ISSUE TITLE
GOL Literally Unplayable

### ISSUE THREAD

**Issue by SuiNom** [joeparkin/joeparkin.com#1]
The GOL implementation does not center "drawings" when the cell size is altered.

Normal 10px Cell Size, image is centered.
<img width="983" alt="2024-10-23 18_35_38-Game of Life — Mozilla Firefox" src="https://github.com/user-attachments/assets/a836a0c7-144b-4871-9b82-cc8e7a11b17d">

20px size draws the image in the bottom right.
<img width="994" alt="2024-10-23 18_35_52-Game of Life — Mozilla Firefox" src="https://github.com/user-attachments/assets/32fbb914-d77c-4d1b-a22d-7f31af80bd1d">

This is literally unplayable.

**Comment by joeparkin** [comment]
Good spot - I will fix this!
